name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config  user.email chaurasiasatyam983@gmail.com
          git config  user.name SatyamChaurasia98
          git remote set-url origin https://b15db7ff26c9e84cc0ddc85d592d815513832955@github.com/SatyamChaurasia98/Forms-assignment.git
          npm run deploy
